# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "8"

cache:
  directories:
    - $HOME/.npm
    - node_modules

install:
  - npm install

# http://docs.travis-ci.com/user/pull-requests/
script:
  - npm test
